INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 130, in anketa_own_contacts_end
    users = list(user['user_id'], context.user_data['anketa'])
TypeError: list expected at most 1 argument, got 2
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 130, in anketa_own_contacts_end
    users = list(user['user_id'], )
TypeError: 'int' object is not iterable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 130, in anketa_own_contacts_end
    users = list(user['user_id'])
TypeError: 'int' object is not iterable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 130, in anketa_own_contacts_end
    users = list(user['user_id'])
TypeError: 'int' object is not iterable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 136, in anketa_own_contacts_end
    worksheet.append_row(users)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1437, in append_row
    return self.append_rows(
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1478, in append_rows
    return self.spreadsheet.values_append(range_label, params, body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 164, in values_append
    r = self.client.request('post', url, params=params, json=body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\client.py", line 61, in request
    response = getattr(self.session, method)(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\projects\bot_diplom\env\lib\site-packages\google\auth\transport\requests.py", line 464, in request
    response = super(AuthorizedSession, self).request(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 469, in prepare_body
    body = complexjson.dumps(json)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 136, in anketa_own_contacts_end
    worksheet.append_row(users)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1437, in append_row
    return self.append_rows(
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1478, in append_rows
    return self.spreadsheet.values_append(range_label, params, body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 164, in values_append
    r = self.client.request('post', url, params=params, json=body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\client.py", line 61, in request
    response = getattr(self.session, method)(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\projects\bot_diplom\env\lib\site-packages\google\auth\transport\requests.py", line 464, in request
    response = super(AuthorizedSession, self).request(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 469, in prepare_body
    body = complexjson.dumps(json)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 137, in anketa_own_contacts_end
    worksheet.append_row(users.values())
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1437, in append_row
    return self.append_rows(
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1478, in append_rows
    return self.spreadsheet.values_append(range_label, params, body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 164, in values_append
    r = self.client.request('post', url, params=params, json=body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\client.py", line 61, in request
    response = getattr(self.session, method)(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\projects\bot_diplom\env\lib\site-packages\google\auth\transport\requests.py", line 464, in request
    response = super(AuthorizedSession, self).request(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 469, in prepare_body
    body = complexjson.dumps(json)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_values is not JSON serializable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 137, in anketa_own_contacts_end
    worksheet.append_row(asd)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1437, in append_row
    return self.append_rows(
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1478, in append_rows
    return self.spreadsheet.values_append(range_label, params, body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 164, in values_append
    r = self.client.request('post', url, params=params, json=body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\client.py", line 61, in request
    response = getattr(self.session, method)(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\projects\bot_diplom\env\lib\site-packages\google\auth\transport\requests.py", line 464, in request
    response = super(AuthorizedSession, self).request(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 469, in prepare_body
    body = complexjson.dumps(json)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_values is not JSON serializable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 137, in anketa_own_contacts_end
    worksheet.append_row(asd)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1437, in append_row
    return self.append_rows(
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 1478, in append_rows
    return self.spreadsheet.values_append(range_label, params, body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\models.py", line 164, in values_append
    r = self.client.request('post', url, params=params, json=body)
  File "c:\projects\bot_diplom\env\lib\site-packages\gspread\client.py", line 61, in request
    response = getattr(self.session, method)(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\projects\bot_diplom\env\lib\site-packages\google\auth\transport\requests.py", line 464, in request
    response = super(AuthorizedSession, self).request(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "c:\projects\bot_diplom\env\lib\site-packages\requests\models.py", line 469, in prepare_body
    body = complexjson.dumps(json)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 134, in anketa_own_contacts_end
    asd = list(users.values([-1]))
TypeError: values() takes no arguments (1 given)
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
