INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_applicant.py", line 125, in anketa_contacts_end
    update.message.reply_text(user_text, reply_markup=main_keyboard(),
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\message.py", line 515, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "<decorator-gen-2>", line 2, in send_message
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\bot.py", line 346, in send_message
    return self._message(url, data, disable_notification=disable_notification,
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\bot.py", line 175, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\utils\request.py", line 330, in post
    result = self._request_wrapper('POST', url,
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\utils\request.py", line 244, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end tag corresponding to start tag b
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_applicant.py", line 125, in anketa_contacts_end
    update.message.reply_text(user_text, reply_markup=main_keyboard(),
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\message.py", line 515, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "<decorator-gen-2>", line 2, in send_message
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\bot.py", line 346, in send_message
    return self._message(url, data, disable_notification=disable_notification,
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\bot.py", line 175, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\utils\request.py", line 330, in post
    result = self._request_wrapper('POST', url,
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\utils\request.py", line 244, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end tag corresponding to start tag b
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_applicant.py", line 125, in anketa_contacts_end
    update.message.reply_text(user_text, reply_markup=main_keyboard(),
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\message.py", line 515, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "<decorator-gen-2>", line 2, in send_message
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\bot.py", line 346, in send_message
    return self._message(url, data, disable_notification=disable_notification,
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\bot.py", line 175, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\utils\request.py", line 330, in post
    result = self._request_wrapper('POST', url,
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\utils\request.py", line 244, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end tag corresponding to start tag b
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 132, in anketa_own_skip
    user_text_own = format_anketa_own(context.user_data['anketa'])
  File "c:\projects\bot_diplom\anketa_prod_owner.py", line 143, in format_anketa_own
    <b>имя фамилия:</b> {anketa['name_own']}
KeyError: 'name_own'
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
